apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-proxy
  labels:
    app.kubernetes.io/component: tower-connect-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tower-connect-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tower-connect-proxy
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: proxy
          image: cr.seqera.io/private/nf-tower-enterprise/data-studio/connect-proxy:0.7.0
          command:
            - caddy
            - run
            - --config
            - /proxy-config/Caddyfile
          env:
            - name: CONNECT_HTTP_PORT
              value: "80"
              # "hostname.domain.cache.amazonaws.com:6379"
            - name: REDIS_SERVER
              value: <REDIS_SERVER>
            - name: REDIS_PREFIX
              value: "connect:session"
            - name: REDIS_TLS_ENABLE
              value: "false"
            - name: REDIS_DB
              value: "1"
              # connect.cloud.example.com
            - name: TOWER_CONNECT_DOMAIN
              value: <TOWER_CONNECT_DOMAIN>
            - name: TOWER_CONNECT_TUNNEL
              value: connect-server:7070
              # "https://cloud.example.com"
            - name: TOWER_BASE_URL
              value: <TOWER_BASE_URL>
            - name: INITIAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: connect-proxy-secret
                  key: INITIAL_ACCESS_TOKEN
            - name: LOCAL_CACHE_TTL
              value: 2m
          ports:
            - containerPort: 80
              name: proxy
          volumeMounts:
            - mountPath: /proxy-config
              name: proxy-config
      volumes:
        - name: proxy-config
          configMap:
            name: connect-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: connect-proxy
  labels:
    app.kubernetes.io/component: tower-connect-proxy
spec:
  type: NodePort
  ports:
    - port: 80
      name: connect-proxy
      targetPort: proxy
  selector:
    app.kubernetes.io/component: tower-connect-proxy